version: "3"

dotenv:
  - .env
  - .env.local

env:
  PORT: 8080

vars:
  container_name: app
  container_tag: latest

tasks:
  dev:
    run: always
    cmds:
      - air

  build:
    deps:
      - task: generate
    cmds:
      - CGO_ENABLED=0 go build -o build/server main.go

  container:
    deps:
      - task: generate
    cmds:
      - docker build -t {{.container_name}}:{{.container_tag}} .

  generate:
    aliases:
      - gen
      - g
    generates:
      - templates/**/*.go
      - views/**/*.go
      - static/**/*.css
    sources:
      - templates/**/*.templ
      - views/**/*.templ
      - tailwind.config.js
      - tailwind.css
    cmds:
      - npx tailwindcss build -i tailwind.css -o static/style.css
      - go run github.com/a-h/templ/cmd/templ@latest generate
      - go generate ./...
